// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CartPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cartPage() {
    // Test name: Cart Page
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1440x812 | 
    driver.manage().window().setSize(new Dimension(1440, 812));
    // 3 | click | css=.css-ullnvh-MuiButtonBase-root-MuiButton-root | 
    driver.findElement(By.cssSelector(".css-ullnvh-MuiButtonBase-root-MuiButton-root")).click();
    // 4 | click | id=:r5: | 
    driver.findElement(By.id(":r5:")).click();
    // 5 | type | id=:r5: | tushar123
    driver.findElement(By.id(":r5:")).sendKeys("tushar123");
    // 6 | click | id=:r7: | 
    driver.findElement(By.id(":r7:")).click();
    // 7 | type | id=:r7: | Tushar@123
    driver.findElement(By.id(":r7:")).sendKeys("Tushar@123");
    // 8 | click | css=.css-3uz8ua-MuiButtonBase-root-MuiButton-root | 
    driver.findElement(By.cssSelector(".css-3uz8ua-MuiButtonBase-root-MuiButton-root")).click();
    // 9 | click | css=.MuiBox-root:nth-child(1) > .react-multi-carousel-list .react-multi-carousel-item:nth-child(14) .css-1e935dx | 
    driver.findElement(By.cssSelector(".MuiBox-root:nth-child(1) > .react-multi-carousel-list .react-multi-carousel-item:nth-child(14) .css-1e935dx")).click();
    // 10 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 11 | mouseOver | css=.MuiButtonBase-root:nth-child(3) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 12 | mouseOver | css=.css-1yj0ph-MuiButtonBase-root-MuiButton-root:nth-child(2) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-1yj0ph-MuiButtonBase-root-MuiButton-root:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 13 | click | css=.css-1yj0ph-MuiButtonBase-root-MuiButton-root:nth-child(2) | 
    driver.findElement(By.cssSelector(".css-1yj0ph-MuiButtonBase-root-MuiButton-root:nth-child(2)")).click();
    // 14 | mouseOver | css=.MuiButtonGroup-lastButton | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonGroup-lastButton"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 15 | click | css=.MuiButtonGroup-lastButton | 
    driver.findElement(By.cssSelector(".MuiButtonGroup-lastButton")).click();
    // 16 | mouseOut | css=.MuiButtonGroup-lastButton | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 17 | mouseOver | css=.css-1pz2rcc-MuiButtonBase-root-MuiButton-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-1pz2rcc-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 18 | click | css=.css-1pz2rcc-MuiButtonBase-root-MuiButton-root | 
    driver.findElement(By.cssSelector(".css-1pz2rcc-MuiButtonBase-root-MuiButton-root")).click();
    // 19 | click | css=.css-g3pe7h > img | 
    driver.findElement(By.cssSelector(".css-g3pe7h > img")).click();
    // 20 | mouseOver | css=.css-g3pe7h > img | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-g3pe7h > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 21 | click | css=.MuiBox-root:nth-child(1) > .react-multi-carousel-list .react-multi-carousel-item:nth-child(12) .css-1e935dx | 
    driver.findElement(By.cssSelector(".MuiBox-root:nth-child(1) > .react-multi-carousel-list .react-multi-carousel-item:nth-child(12) .css-1e935dx")).click();
    // 22 | mouseOver | css=.MuiButtonBase-root:nth-child(3) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 23 | click | css=.css-1yj0ph-MuiButtonBase-root-MuiButton-root:nth-child(2) | 
    driver.findElement(By.cssSelector(".css-1yj0ph-MuiButtonBase-root-MuiButton-root:nth-child(2)")).click();
    // 24 | click | css=.css-128nsc3-MuiButtonBase-root-MuiButton-root | 
    driver.findElement(By.cssSelector(".css-128nsc3-MuiButtonBase-root-MuiButton-root")).click();
  }
}
