// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ForgotPasswordPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void forgotPasswordPage() {
    // Test name: Forgot Password Page
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1440x812 | 
    driver.manage().window().setSize(new Dimension(1440, 812));
    // 3 | click | css=.css-ullnvh-MuiButtonBase-root-MuiButton-root | 
    driver.findElement(By.cssSelector(".css-ullnvh-MuiButtonBase-root-MuiButton-root")).click();
    // 4 | click | id=:r5: | 
    driver.findElement(By.id(":r5:")).click();
    // 5 | mouseOver | css=.css-3uz8ua-MuiButtonBase-root-MuiButton-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-3uz8ua-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | mouseOver | css=.css-1ovnlut-MuiButtonBase-root-MuiButton-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-1ovnlut-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | type | id=:r5: | hello
    driver.findElement(By.id(":r5:")).sendKeys("hello");
    // 8 | click | css=.css-1ovnlut-MuiButtonBase-root-MuiButton-root | 
    driver.findElement(By.cssSelector(".css-1ovnlut-MuiButtonBase-root-MuiButton-root")).click();
    // 9 | mouseOver | css=.MuiButton-text | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | click | css=.css-q6y1rd | 
    driver.findElement(By.cssSelector(".css-q6y1rd")).click();
    // 11 | type | id=:r5: | bhavyajkp@gmail.com
    driver.findElement(By.id(":r5:")).sendKeys("bhavyajkp@gmail.com");
    // 12 | click | css=.MuiButton-text | 
    driver.findElement(By.cssSelector(".MuiButton-text")).click();
    // 13 | click | id=:r5: | 
    driver.findElement(By.id(":r5:")).click();
    // 14 | type | id=:r5: | 3456
    driver.findElement(By.id(":r5:")).sendKeys("3456");
    // 15 | mouseDown | id=:r9: | 
    {
      WebElement element = driver.findElement(By.id(":r9:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 16 | mouseUp | id=:r9:-label | 
    {
      WebElement element = driver.findElement(By.id(":r9:-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 17 | click | css=.MuiFormControl-root:nth-child(2) | 
    driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(2)")).click();
    // 18 | type | id=:r9: | vue
    driver.findElement(By.id(":r9:")).sendKeys("vue");
    // 19 | click | id=:r5: | 
    driver.findElement(By.id(":r5:")).click();
    // 20 | mouseOver | css=.MuiButton-text | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 21 | type | id=:r5: | wb
    driver.findElement(By.id(":r5:")).sendKeys("wb");
  }
}
