// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HeaderTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void header() {
    // Test name: Header
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://software-engineering-project-kohl.vercel.app/");
    // 2 | setWindowSize | 1440x812 | 
    driver.manage().window().setSize(new Dimension(1440, 812));
    // 3 | click | css=.css-g3pe7h > img | 
    driver.findElement(By.cssSelector(".css-g3pe7h > img")).click();
    // 4 | click | css=.css-aae3xl | 
    driver.findElement(By.cssSelector(".css-aae3xl")).click();
    // 5 | mouseDown | css=.MuiSelect-select | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiSelect-select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 6 | mouseUp | css=.MuiBackdrop-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 7 | click | css=body | 
    driver.findElement(By.cssSelector("body")).click();
    // 8 | click | css=.MuiBackdrop-root | 
    driver.findElement(By.cssSelector(".MuiBackdrop-root")).click();
    // 9 | mouseDown | css=.MuiSelect-select | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiSelect-select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 10 | mouseUp | css=.MuiBackdrop-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 11 | click | css=body | 
    driver.findElement(By.cssSelector("body")).click();
    // 12 | click | css=.MuiMenuItem-root:nth-child(2) | 
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    // 13 | click | css=.css-vvqekh | 
    driver.findElement(By.cssSelector(".css-vvqekh")).click();
    // 14 | click | css=.MuiDialog-container | 
    driver.findElement(By.cssSelector(".MuiDialog-container")).click();
    // 15 | click | css=.css-ktqfmw | 
    driver.findElement(By.cssSelector(".css-ktqfmw")).click();
    // 16 | mouseOver | css=.css-1j5lvh1 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-1j5lvh1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 17 | click | css=.css-1xdkgnn > img | 
    driver.findElement(By.cssSelector(".css-1xdkgnn > img")).click();
    // 18 | mouseOver | css=.css-16bg4h6 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-16bg4h6"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 19 | mouseOver | css=.css-ktqfmw | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-ktqfmw"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 20 | click | css=.MuiButton-text | 
    driver.findElement(By.cssSelector(".MuiButton-text")).click();
    // 21 | click | css=.MuiDialog-container | 
    driver.findElement(By.cssSelector(".MuiDialog-container")).click();
    // 22 | click | css=.css-hng5kb | 
    driver.findElement(By.cssSelector(".css-hng5kb")).click();
  }
}
