// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HomePageafterLoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void homePageafterLogin() {
    // Test name: HomePage after Login
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1440x812 | 
    driver.manage().window().setSize(new Dimension(1440, 812));
    // 3 | mouseOver | css=.css-11sgoyl-MuiButtonBase-root-MuiButton-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-11sgoyl-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | css=.css-11sgoyl-MuiButtonBase-root-MuiButton-root | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | mouseOver | css=.css-u05wtg-MuiSvgIcon-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-u05wtg-MuiSvgIcon-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | click | css=.css-ullnvh-MuiButtonBase-root-MuiButton-root | 
    driver.findElement(By.cssSelector(".css-ullnvh-MuiButtonBase-root-MuiButton-root")).click();
    // 7 | click | id=:r5: | 
    driver.findElement(By.id(":r5:")).click();
    // 8 | type | id=:r5: | tushar123
    driver.findElement(By.id(":r5:")).sendKeys("tushar123");
    // 9 | mouseOver | css=.css-3uz8ua-MuiButtonBase-root-MuiButton-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-3uz8ua-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | type | id=:r7: | Tushar@123
    driver.findElement(By.id(":r7:")).sendKeys("Tushar@123");
    // 11 | click | css=.css-3uz8ua-MuiButtonBase-root-MuiButton-root | 
    driver.findElement(By.cssSelector(".css-3uz8ua-MuiButtonBase-root-MuiButton-root")).click();
    // 12 | click | css=.react-multi-carousel-list:nth-child(1) > .react-multiple-carousel__arrow--right | 
    driver.findElement(By.cssSelector(".react-multi-carousel-list:nth-child(1) > .react-multiple-carousel__arrow--right")).click();
    // 13 | click | css=.react-multi-carousel-list:nth-child(1) > .react-multiple-carousel__arrow--right | 
    driver.findElement(By.cssSelector(".react-multi-carousel-list:nth-child(1) > .react-multiple-carousel__arrow--right")).click();
    // 14 | click | css=.react-multi-carousel-list:nth-child(1) > .react-multiple-carousel__arrow--right | 
    driver.findElement(By.cssSelector(".react-multi-carousel-list:nth-child(1) > .react-multiple-carousel__arrow--right")).click();
    // 15 | click | css=.MuiBox-root:nth-child(1) > .react-multi-carousel-list .react-multi-carousel-item:nth-child(14) .css-1e935dx | 
    driver.findElement(By.cssSelector(".MuiBox-root:nth-child(1) > .react-multi-carousel-list .react-multi-carousel-item:nth-child(14) .css-1e935dx")).click();
    // 16 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 17 | click | css=.css-g3pe7h > img | 
    driver.findElement(By.cssSelector(".css-g3pe7h > img")).click();
  }
}
