// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PaymentPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void paymentPage() {
    // Test name: Payment Page
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1440x812 | 
    driver.manage().window().setSize(new Dimension(1440, 812));
    // 3 | click | css=.MuiBox-root:nth-child(1) > .react-multi-carousel-list .react-multi-carousel-item:nth-child(13) .css-1e935dx | 
    driver.findElement(By.cssSelector(".MuiBox-root:nth-child(1) > .react-multi-carousel-list .react-multi-carousel-item:nth-child(13) .css-1e935dx")).click();
    // 4 | mouseOver | css=.MuiButtonBase-root:nth-child(3) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 5 | click | css=.MuiButtonBase-root:nth-child(3) | 
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3)")).click();
    // 6 | click | name=cardNumber | 
    driver.findElement(By.name("cardNumber")).click();
    // 7 | type | name=cardNumber | 5345 4643 6365 6564
    driver.findElement(By.name("cardNumber")).sendKeys("5345 4643 6365 6564");
    // 8 | click | name=expiryDate | 
    driver.findElement(By.name("expiryDate")).click();
    // 9 | type | name=expiryDate | 10/25
    driver.findElement(By.name("expiryDate")).sendKeys("10/25");
    // 10 | click | name=cvv | 
    driver.findElement(By.name("cvv")).click();
    // 11 | type | name=cvv | 123
    driver.findElement(By.name("cvv")).sendKeys("123");
    // 12 | click | name=nameOnCard | 
    driver.findElement(By.name("nameOnCard")).click();
    // 13 | type | name=nameOnCard | Tushar
    driver.findElement(By.name("nameOnCard")).sendKeys("Tushar");
    // 14 | type | name=nameOnCard | Tushar Mori
    driver.findElement(By.name("nameOnCard")).sendKeys("Tushar Mori");
    // 15 | click | css=button:nth-child(4) | 
    driver.findElement(By.cssSelector("button:nth-child(4)")).click();
    // 16 | click | css=.btn:nth-child(1) | 
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    // 17 | click | css=.back-to-home-button | 
    driver.findElement(By.cssSelector(".back-to-home-button")).click();
    // 18 | mouseOver | css=.css-ullnvh-MuiButtonBase-root-MuiButton-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-ullnvh-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 19 | click | css=.MuiBox-root:nth-child(1) > .react-multi-carousel-list .react-multi-carousel-item:nth-child(13) .css-1e935dx | 
    driver.findElement(By.cssSelector(".MuiBox-root:nth-child(1) > .react-multi-carousel-list .react-multi-carousel-item:nth-child(13) .css-1e935dx")).click();
    // 20 | mouseOver | css=.MuiButtonBase-root:nth-child(3) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 21 | click | css=.MuiButtonBase-root:nth-child(3) | 
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3)")).click();
    // 22 | click | css=button:nth-child(2) | 
    driver.findElement(By.cssSelector("button:nth-child(2)")).click();
    // 23 | click | css=button:nth-child(3) | 
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    // 24 | click | name=upiId | 
    driver.findElement(By.name("upiId")).click();
    // 25 | type | name=upiId | 123455@upi
    driver.findElement(By.name("upiId")).sendKeys("123455@upi");
    // 26 | click | css=button:nth-child(4) | 
    driver.findElement(By.cssSelector("button:nth-child(4)")).click();
    // 27 | click | css=.btn-secondary | 
    driver.findElement(By.cssSelector(".btn-secondary")).click();
  }
}
