// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchbarTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchbar() {
    // Test name: Searchbar
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1440x812 | 
    driver.manage().window().setSize(new Dimension(1440, 812));
    // 3 | click | css=.css-yimnyd-MuiInputBase-input | 
    driver.findElement(By.cssSelector(".css-yimnyd-MuiInputBase-input")).click();
    // 4 | type | css=.css-yimnyd-MuiInputBase-input | wa
    driver.findElement(By.cssSelector(".css-yimnyd-MuiInputBase-input")).sendKeys("wa");
    // 5 | click | css=.MuiListItem-root > a | 
    driver.findElement(By.cssSelector(".MuiListItem-root > a")).click();
    // 6 | click | css=.css-g3pe7h > img | 
    driver.findElement(By.cssSelector(".css-g3pe7h > img")).click();
    // 7 | mouseDown | css=.MuiSelect-select | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiSelect-select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 8 | mouseUp | css=.MuiBackdrop-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 9 | click | css=body | 
    driver.findElement(By.cssSelector("body")).click();
    // 10 | click | css=.MuiMenuItem-root:nth-child(2) | 
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    // 11 | mouseDown | css=.MuiSelect-select | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiSelect-select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 12 | mouseUp | css=.MuiBackdrop-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 13 | click | css=body | 
    driver.findElement(By.cssSelector("body")).click();
    // 14 | click | css=.MuiMenuItem-root:nth-child(3) | 
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(3)")).click();
  }
}
