// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SellerPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sellerPage() {
    // Test name: Seller Page
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1440x812 | 
    driver.manage().window().setSize(new Dimension(1440, 812));
    // 3 | click | css=.css-11sgoyl-MuiButtonBase-root-MuiButton-root | 
    driver.findElement(By.cssSelector(".css-11sgoyl-MuiButtonBase-root-MuiButton-root")).click();
    // 4 | click | css=.css-ioqfxg-MuiButtonBase-root-MuiButton-root | 
    driver.findElement(By.cssSelector(".css-ioqfxg-MuiButtonBase-root-MuiButton-root")).click();
    // 5 | mouseOver | css=.css-3uz8ua-MuiButtonBase-root-MuiButton-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-3uz8ua-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | mouseOver | css=.css-pjbrry-MuiButtonBase-root-MuiButton-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-pjbrry-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | click | css=.css-ii44g4-MuiTypography-root | 
    driver.findElement(By.cssSelector(".css-ii44g4-MuiTypography-root")).click();
    // 8 | mouseOver | css=.MuiButton-text | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | click | id=:r9: | 
    driver.findElement(By.id(":r9:")).click();
    // 10 | type | id=:r9: | heyy
    driver.findElement(By.id(":r9:")).sendKeys("heyy");
    // 11 | click | id=:rd: | 
    driver.findElement(By.id(":rd:")).click();
    // 12 | type | id=:rd: | hellooo
    driver.findElement(By.id(":rd:")).sendKeys("hellooo");
    // 13 | click | id=:rb: | 
    driver.findElement(By.id(":rb:")).click();
    // 14 | type | id=:rb: | tusharmori543@gmail.com
    driver.findElement(By.id(":rb:")).sendKeys("tusharmori543@gmail.com");
    // 15 | click | id=:rb: | 
    driver.findElement(By.id(":rb:")).click();
    // 16 | type | id=:rb: | tusharmori54@gmail.com
    driver.findElement(By.id(":rb:")).sendKeys("tusharmori54@gmail.com");
    // 17 | click | id=:rf: | 
    driver.findElement(By.id(":rf:")).click();
    // 18 | click | id=:rb: | 
    driver.findElement(By.id(":rb:")).click();
    // 19 | type | id=:rb: | tusharmori54
    driver.findElement(By.id(":rb:")).sendKeys("tusharmori54");
    // 20 | click | id=:rf: | 
    driver.findElement(By.id(":rf:")).click();
    // 21 | type | id=:rf: | tusharmori543@gmail.com
    driver.findElement(By.id(":rf:")).sendKeys("tusharmori543@gmail.com");
    // 22 | click | id=:rf: | 
    driver.findElement(By.id(":rf:")).click();
    // 23 | type | id=:rf: | tusharmori54@gmail.com
    driver.findElement(By.id(":rf:")).sendKeys("tusharmori54@gmail.com");
    // 24 | click | id=:rh: | 
    driver.findElement(By.id(":rh:")).click();
    // 25 | mouseOver | css=.MuiIconButton-edgeEnd path | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiIconButton-edgeEnd path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 26 | click | css=.MuiIconButton-edgeEnd path | 
    driver.findElement(By.cssSelector(".MuiIconButton-edgeEnd path")).click();
    // 27 | click | id=:rj: | 
    driver.findElement(By.id(":rj:")).click();
    // 28 | type | id=:rj: | +91 98187-65435
    driver.findElement(By.id(":rj:")).sendKeys("+91 98187-65435");
    // 29 | click | css=.MuiButton-text | 
    driver.findElement(By.cssSelector(".MuiButton-text")).click();
    // 30 | mouseOver | css=.css-enjmhf-MuiButtonBase-root-MuiButton-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-enjmhf-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 31 | click | css=.css-18pvhag-MuiSvgIcon-root | 
    driver.findElement(By.cssSelector(".css-18pvhag-MuiSvgIcon-root")).click();
    // 32 | mouseOver | css=.css-enjmhf-MuiButtonBase-root-MuiButton-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-enjmhf-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 33 | click | css=.css-7xrepp-MuiSvgIcon-root | 
    driver.findElement(By.cssSelector(".css-7xrepp-MuiSvgIcon-root")).click();
    // 34 | click | css=.MuiButton-containedSecondary | 
    driver.findElement(By.cssSelector(".MuiButton-containedSecondary")).click();
    // 35 | click | css=.MuiGrid-root:nth-child(1) .MuiTypography-root:nth-child(2) | 
    driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(1) .MuiTypography-root:nth-child(2)")).click();
  }
}
