// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SignupPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signupPage() {
    // Test name: Signup Page
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1440x812 | 
    driver.manage().window().setSize(new Dimension(1440, 812));
    // 3 | click | css=.css-ullnvh-MuiButtonBase-root-MuiButton-root | 
    driver.findElement(By.cssSelector(".css-ullnvh-MuiButtonBase-root-MuiButton-root")).click();
    // 4 | click | css=.css-ii44g4-MuiTypography-root | 
    driver.findElement(By.cssSelector(".css-ii44g4-MuiTypography-root")).click();
    // 5 | click | id=:r5: | 
    driver.findElement(By.id(":r5:")).click();
    // 6 | type | id=:r5: | tushar
    driver.findElement(By.id(":r5:")).sendKeys("tushar");
    // 7 | mouseDown | id=:r9: | 
    {
      WebElement element = driver.findElement(By.id(":r9:"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 8 | mouseUp | id=:r9:-label | 
    {
      WebElement element = driver.findElement(By.id(":r9:-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 9 | click | css=.MuiFormControl-root:nth-child(2) | 
    driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(2)")).click();
    // 10 | type | id=:r9: | Mori
    driver.findElement(By.id(":r9:")).sendKeys("Mori");
    // 11 | click | id=:r7: | 
    driver.findElement(By.id(":r7:")).click();
    // 12 | type | id=:r7: | tushar456
    driver.findElement(By.id(":r7:")).sendKeys("tushar456");
    // 13 | click | id=:rb: | 
    driver.findElement(By.id(":rb:")).click();
    // 14 | type | id=:rb: | tushare@gmail.com
    driver.findElement(By.id(":rb:")).sendKeys("tushare@gmail.com");
    // 15 | click | id=:rd: | 
    driver.findElement(By.id(":rd:")).click();
    // 16 | type | id=:rd: | tushar!234T
    driver.findElement(By.id(":rd:")).sendKeys("tushar!234T");
    // 17 | click | id=:rf: | 
    driver.findElement(By.id(":rf:")).click();
    // 18 | type | id=:rf: | +91 99898-95953
    driver.findElement(By.id(":rf:")).sendKeys("+91 99898-95953");
    // 19 | click | css=.MuiButton-text | 
    driver.findElement(By.cssSelector(".MuiButton-text")).click();
  }
}
